"""Fuse Mahek's InterviewTranscript with this module's DocumentBundle output into
one HistorySummary — the artefact the whole project is judged on.

Interview-side sections are built against the REAL ontology question ids (see
`interview_sections.py`), reviewed on 2026-08-22 — not guessed keys. The one
deliberate remaining gap is `ayurvedic_assessment` (Dashavidha Pariksha), which
needs AIIA-practitioner-reviewed content mapping the ontology itself calls for
and this module does not have; see `interview_sections.py`'s docstring.

What's built and real:
* drugs_allergy, prior_investigations — from `summary.document_sections`.
* chief_complaint, hpi, past_medical, past_surgical, family, personal, ros —
  from `summary.interview_sections`, against real ontology question ids.
* Medication contradictions — from `summary.contradictions`, checking the real
  `rx.current` structured answer first, narration as fallback.
* Red flags, exploration, gaps, abnormal values, interactions — direct
  pass-through from structures both halves already produce.
* ayurvedic_assessment — an honest gap section, not autogenerated content,
  per the platform's AYUSH-review rule.
"""
from __future__ import annotations

from sanjeevani_ml.schemas import DocumentBundle, HistorySummary, InterviewTranscript
from sanjeevani_ml.summary.contradictions import detect_medication_contradictions
from sanjeevani_ml.summary.document_sections import build_document_only_sections
from sanjeevani_ml.summary.interview_sections import build_interview_sections


def build_history_summary(
    transcript: InterviewTranscript, bundle: DocumentBundle
) -> HistorySummary:
    """Assemble the physician-facing draft summary from both halves of the pipeline.

    Never raises: a missing or empty transcript (e.g. the patient abandoned the
    interview) still produces a valid HistorySummary with document-only sections
    filled in and interview sections showing an honest "not answered" note —
    the kiosk's degrade-never-fail principle applies here too.

    Args:
        transcript: Mahek's InterviewTranscript for this session.
        bundle: This module's own DocumentBundle for the same session.

    Returns:
        A HistorySummary with `status="draft"` — never anything else. The
        physician accepts, amends, or rejects; this function never phrases
        anything as a diagnosis.
    """
    document_sections = build_document_only_sections(bundle)
    interview_sections = build_interview_sections(transcript)

    contradictions = detect_medication_contradictions(transcript, bundle)

    gaps = list(transcript.unanswered)
    gaps.extend(bundle.warnings)
    gaps.extend(transcript.exploration.not_explored)
    for section in interview_sections:
        if section.confidence == 0.0:
            gaps.append(f"{section.heading}: not answered or not reached in this interview")

    all_sections = [*document_sections, *interview_sections]
    confidences = [s.confidence for s in all_sections if s.confidence > 0]
    mean_confidence = sum(confidences) / len(confidences) if confidences else 0.0

    return HistorySummary(
        session_id=transcript.session_id,
        sections=all_sections,
        red_flags=list(transcript.red_flags),
        abnormal_values=list(bundle.abnormal_values),
        interactions=list(bundle.interactions),
        contradictions=contradictions,
        exploration=transcript.exploration,
        gaps=gaps,
        # Spoken confirmation needs Bhashini/AI4Bharat TTS (Mahek/Ronit's side) to
        # actually speak this — this module's job is only to hand over clean text,
        # not to synthesize audio.
        patient_confirmation={
            "en": "We have recorded your history and the documents you provided. "
                  "Please let the staff know if anything is missing or incorrect."
        },
        fhir_bundle={},  # wired separately at the service layer, alongside
                         # fhir.bundle.build_document_bundle_fhir
        mean_confidence=mean_confidence,
        engine="summary-v1",
    )
